export const Paths = {
  home: "/",
  login: "/login",
  signup: "/signup",
  todo: "/todos",
  allUsers: "/allusers",
  allTodos: "/alltodos",
  addUser: "/adduser",
  userTodos: "/todos/main",
  todoAdd: "/todos/add",
  todoEdit: "/todos/edit",
  user: "/users",
  userEdit: "/users/edit",
  createUser: "/users/createuser",
  status: "/status",
} as const;
