export const enum ErrorType {
  USER_NOT_FOUND = 'No User found with that ID!',
  TODO_NOT_FOUND = 'No Todo found with that ID!',
  USER_NOT_FOUND_EMAIL = 'There is no user with that email address',
  NO_EMAIL_AND_PASSWORD = 'Please provide email and password!',
  INCORRECT_EMAIL_OR_PASSWORD = 'Incorrect email or password!',
  INCORRECT_PASSWORD = 'Your current password is wrong!',
  ERROR_WITH_EMAIL = 'There was an error sending the email. try later!',
  UNAUTHORIZED_ACCESS = 'You do not have permisson to perform this action!',
  LOGIN_PROMPT = 'You are not logged in. Please log in!',
  TOKEN_USER_EXPIRY = 'The user belonging to this token does no longer exist!',
  INVALID_TOKEN = 'This is invalid token!',
  INVALID_OR_EXPIRED_TOKEN = 'Token is invalid or has expired',
  EMAIL_ALREADY_EXISTS = 'This Email is already exists, please provide another email!',
  NOT_SAME_PASSWORD = 'Passwords are not the same!',
  SERVER_ERROR = 500,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  NOT_FOUND = 404,
}
